fix server-side algoliasearch type imports for SearchClient and SearchIndex
causes build-time errors in consuming sites
node_modules/.pnpm/svelte-algolia@0.3.1/node_modules/svelte-algolia/server-side.js:1
import algoliasearch, { SearchClient, SearchIndex } from 'algoliasearch';
                        ^^^^^^^^^^^^
SyntaxError: Named export 'SearchClient' not found. The requested module 'algoliasearch' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'algoliasearch';
const { SearchClient, SearchIndex } = pkg;